### ISSUE TITLE
Get all submissions fails on Windows

### ISSUE THREAD

**Issue by yurirocha15** [yurirocha15/leetcode2github#17]
There seem to have some issues with the subprocess library.

**Comment by sungho-joo** [comment]
when running "make get-all-submissions", error occurs while using start method of SyncManager()

error message

python scripts/leetcode_tools.py get-all-submissions
("Can't pickle local object 'get_all_submissions.<locals>.mgr_init'",)
Traceback (most recent call last):
  File "scripts/leetcode_tools.py", line 197, in <module>
    clize.run(get_question, submit_question, leetcode_login, get_all_submissions, remove_question)
  File "C:\Users\trian\.conda\envs\leetcode\lib\site-packages\sigtools\modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\trian\.conda\envs\leetcode\lib\site-packages\clize\runner.py", line 363, in run
    ret = cli(*args)
  File "C:\Users\trian\.conda\envs\leetcode\lib\site-packages\clize\runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "C:\Users\trian\.conda\envs\leetcode\lib\site-packages\clize\runner.py", line 262, in _cli
    return func('{0} {1}'.format(name, command), *args)
  File "C:\Users\trian\.conda\envs\leetcode\lib\site-packages\clize\runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "scripts/leetcode_tools.py", line 170, in get_all_submissions
    manager.shutdown()
AttributeError: 'SyncManager' object has no attribute 'shutdown'
make: *** [Makefile:6: get-all-submissions] Error 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\trian\.conda\envs\leetcode\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "C:\Users\trian\.conda\envs\leetcode\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] 액세스가 거부되었습니다

and error happens in the line below

https://github.com/yurirocha15/leetcode-practice-python/blob/7be075175e566f47d33d76e6065f2b2650b46b3d/scripts/leetcode_tools.py#L115

it seems this stackoverflow link(https://stackoverflow.com/questions/9670926/multiprocessing-on-windows-breaks) is relevant issue. 

It seems to me this error occurs because 'mgr_init' passed to start method is not picklable.

I'm working on it but if you have idea, please tell me.

@yurirocha15

**Comment by sungho-joo** [comment]
Checked with windows machine.
No problem getting submissions from the server.
